import type { Scenario } from '../scenario';
import { bindKey, declareExchange, declareQueue, publish, queue } from './helpers';

/**
 * Seed delivery scenarios, including the two bugs of the original simulator that this project is a regression test
 * for (ADR-0002, ADR-0015). Messages are published through the default exchange, with the queue name as the key.
 */
export const DELIVERY_SCENARIOS: readonly Scenario[] = [
  {
    id: 'delivery/round-robin-between-consumers',
    kind: 'delivery',
    title: 'Messages are dealt out to the consumers of a queue in turn (ADR-0008, rule 14)',
    steps: [
      declareQueue('work'),
      { op: 'channel.open', channel: 'ch1' },
      { op: 'channel.open', channel: 'ch2' },
      { op: 'basic.consume', channel: 'ch1', queue: 'work', consumer: 'c1', ack: 'auto' },
      { op: 'basic.consume', channel: 'ch2', queue: 'work', consumer: 'c2', ack: 'auto' },
      publish('', 'work', 'm1'),
      publish('', 'work', 'm2'),
      publish('', 'work', 'm3'),
      publish('', 'work', 'm4'),
      { op: 'await.deliveries', count: 4 },
    ],
  },
  {
    id: 'delivery/prefetch-holds-messages-back-until-an-ack',
    kind: 'delivery',
    title: 'A consumer with a full prefetch window gets nothing more until it acknowledges (ADR-0008, rules 14 and 15)',
    steps: [
      declareQueue('work'),
      { op: 'channel.open', channel: 'ch1', prefetch: 2 },
      { op: 'channel.open', channel: 'ch2', prefetch: 1 },
      { op: 'basic.consume', channel: 'ch1', queue: 'work', consumer: 'c1', ack: 'manual' },
      { op: 'basic.consume', channel: 'ch2', queue: 'work', consumer: 'c2', ack: 'manual' },
      publish('', 'work', 'm1'),
      publish('', 'work', 'm2'),
      publish('', 'work', 'm3'),
      publish('', 'work', 'm4'),
      publish('', 'work', 'm5'),
      { op: 'await.deliveries', count: 3 },
      { op: 'basic.ack', consumer: 'c2' },
      { op: 'await.deliveries', count: 4 },
    ],
  },
  {
    id: 'delivery/issue-10-a-message-goes-to-one-consumer-only',
    kind: 'delivery',
    title: 'With two consumers on a queue, the first message goes to exactly one of them',
    origin: 'RabbitMQSimulator/RabbitMQSimulator#10',
    steps: [
      declareQueue('jobs'),
      { op: 'channel.open', channel: 'ch1' },
      { op: 'channel.open', channel: 'ch2' },
      { op: 'basic.consume', channel: 'ch1', queue: 'jobs', consumer: 'c1', ack: 'auto' },
      { op: 'basic.consume', channel: 'ch2', queue: 'jobs', consumer: 'c2', ack: 'auto' },
      publish('', 'jobs', 'm1'),
      { op: 'await.deliveries', count: 1 },
      publish('', 'jobs', 'm2'),
      { op: 'await.deliveries', count: 2 },
    ],
  },
  {
    id: 'delivery/issue-18-a-removed-consumer-gets-nothing-more',
    kind: 'delivery',
    title:
      'Removing a consumer closes its channel: its unacked message is requeued as redelivered, and nothing else reaches it',
    origin: 'RabbitMQSimulator/RabbitMQSimulator#18',
    steps: [
      declareQueue('jobs'),
      { op: 'channel.open', channel: 'ch1', prefetch: 1 },
      { op: 'channel.open', channel: 'ch2', prefetch: 1 },
      { op: 'basic.consume', channel: 'ch1', queue: 'jobs', consumer: 'c1', ack: 'manual' },
      { op: 'basic.consume', channel: 'ch2', queue: 'jobs', consumer: 'c2', ack: 'manual' },
      publish('', 'jobs', 'm1'),
      publish('', 'jobs', 'm2'),
      publish('', 'jobs', 'm3'),
      { op: 'await.deliveries', count: 2 },
      { op: 'channel.close', channel: 'ch1' },
      publish('', 'jobs', 'm4'),
      { op: 'basic.ack', consumer: 'c2' },
      { op: 'await.deliveries', count: 3 },
    ],
  },
  {
    id: 'delivery/cancel-keeps-unacked-messages',
    kind: 'delivery',
    title:
      'Cancelling a consumer does not requeue its unacked messages, and it can still acknowledge them (ADR-0008, rule 16)',
    steps: [
      declareQueue('jobs'),
      { op: 'channel.open', channel: 'ch1', prefetch: 1 },
      { op: 'basic.consume', channel: 'ch1', queue: 'jobs', consumer: 'c1', ack: 'manual' },
      publish('', 'jobs', 'm1'),
      publish('', 'jobs', 'm2'),
      { op: 'await.deliveries', count: 1 },
      { op: 'basic.cancel', consumer: 'c1' },
      { op: 'basic.ack', consumer: 'c1' },
    ],
  },
  {
    id: 'delivery/auto-ack-ignores-prefetch',
    kind: 'delivery',
    title:
      'A consumer that acknowledges automatically is given every message, whatever the prefetch of its channel (ADR-0008, rule 15)',
    steps: [
      declareQueue('jobs'),
      { op: 'channel.open', channel: 'ch1', prefetch: 1 },
      { op: 'basic.consume', channel: 'ch1', queue: 'jobs', consumer: 'c1', ack: 'auto' },
      publish('', 'jobs', 'm1'),
      publish('', 'jobs', 'm2'),
      publish('', 'jobs', 'm3'),
      { op: 'await.deliveries', count: 3 },
    ],
  },
  {
    id: 'delivery/prefetch-zero-has-no-limit',
    kind: 'delivery',
    title:
      'A prefetch of 0 is no limit: a consumer that acknowledges by hand is given every message (ADR-0008, rule 15)',
    steps: [
      declareQueue('jobs'),
      { op: 'channel.open', channel: 'ch1', prefetch: 0 },
      { op: 'basic.consume', channel: 'ch1', queue: 'jobs', consumer: 'c1', ack: 'manual' },
      publish('', 'jobs', 'm1'),
      publish('', 'jobs', 'm2'),
      publish('', 'jobs', 'm3'),
      publish('', 'jobs', 'm4'),
      publish('', 'jobs', 'm5'),
      { op: 'await.deliveries', count: 5 },
    ],
  },
  {
    id: 'delivery/a-consumer-that-joins-late-takes-its-turn',
    kind: 'delivery',
    title:
      'A consumer that joins a queue that has been served by another is added behind it, and the messages are dealt out in turn from then on (ADR-0008, rule 14)',
    steps: [
      declareQueue('jobs'),
      { op: 'channel.open', channel: 'ch1' },
      { op: 'channel.open', channel: 'ch2' },
      { op: 'basic.consume', channel: 'ch1', queue: 'jobs', consumer: 'c1', ack: 'auto' },
      publish('', 'jobs', 'm1'),
      publish('', 'jobs', 'm2'),
      { op: 'await.deliveries', count: 2 },
      { op: 'basic.consume', channel: 'ch2', queue: 'jobs', consumer: 'c2', ack: 'auto' },
      publish('', 'jobs', 'm3'),
      publish('', 'jobs', 'm4'),
      publish('', 'jobs', 'm5'),
      publish('', 'jobs', 'm6'),
      { op: 'await.deliveries', count: 6 },
    ],
  },
  {
    id: 'delivery/acknowledging-does-not-change-the-order-in-which-consumers-are-served',
    kind: 'delivery',
    title:
      'A consumer that is full, and has not been tried since, keeps its place in the turn: acknowledging in another order does not change who is served first (ADR-0008, rule 14)',
    steps: [
      declareQueue('jobs'),
      { op: 'channel.open', channel: 'ch1', prefetch: 1 },
      { op: 'channel.open', channel: 'ch2', prefetch: 1 },
      { op: 'channel.open', channel: 'ch3', prefetch: 1 },
      { op: 'basic.consume', channel: 'ch1', queue: 'jobs', consumer: 'c1', ack: 'manual' },
      { op: 'basic.consume', channel: 'ch2', queue: 'jobs', consumer: 'c2', ack: 'manual' },
      { op: 'basic.consume', channel: 'ch3', queue: 'jobs', consumer: 'c3', ack: 'manual' },
      publish('', 'jobs', 'm1'),
      publish('', 'jobs', 'm2'),
      publish('', 'jobs', 'm3'),
      { op: 'await.deliveries', count: 3 },
      { op: 'basic.ack', consumer: 'c3' },
      { op: 'basic.ack', consumer: 'c1' },
      { op: 'basic.ack', consumer: 'c2' },
      publish('', 'jobs', 'm4'),
      publish('', 'jobs', 'm5'),
      publish('', 'jobs', 'm6'),
      { op: 'await.deliveries', count: 6 },
    ],
  },
  {
    id: 'delivery/a-consumer-that-was-full-comes-back-behind-the-others',
    kind: 'delivery',
    title:
      'A consumer that was found to be full is taken out of the turn, and comes back at the end of it when an acknowledgement gives it room (ADR-0008, rule 14)',
    steps: [
      declareQueue('jobs'),
      { op: 'channel.open', channel: 'ch1', prefetch: 1 },
      { op: 'channel.open', channel: 'ch2', prefetch: 5 },
      { op: 'basic.consume', channel: 'ch1', queue: 'jobs', consumer: 'c1', ack: 'manual' },
      { op: 'basic.consume', channel: 'ch2', queue: 'jobs', consumer: 'c2', ack: 'manual' },
      publish('', 'jobs', 'm1'),
      publish('', 'jobs', 'm2'),
      publish('', 'jobs', 'm3'),
      { op: 'await.deliveries', count: 3 },
      { op: 'basic.ack', consumer: 'c1' },
      publish('', 'jobs', 'm4'),
      publish('', 'jobs', 'm5'),
      { op: 'await.deliveries', count: 5 },
    ],
  },
  {
    id: 'delivery/requeued-messages-go-back-in-their-places',
    kind: 'delivery',
    title:
      'The messages of a channel that is closed go back to the front of their queue in their old order, redelivered, ahead of what came after them (ADR-0008, rule 16)',
    steps: [
      declareQueue('jobs'),
      { op: 'channel.open', channel: 'ch1', prefetch: 3 },
      { op: 'channel.open', channel: 'ch2' },
      { op: 'basic.consume', channel: 'ch1', queue: 'jobs', consumer: 'c1', ack: 'manual' },
      publish('', 'jobs', 'm1'),
      publish('', 'jobs', 'm2'),
      publish('', 'jobs', 'm3'),
      publish('', 'jobs', 'm4'),
      publish('', 'jobs', 'm5'),
      { op: 'await.deliveries', count: 3 },
      { op: 'channel.close', channel: 'ch1' },
      { op: 'basic.consume', channel: 'ch2', queue: 'jobs', consumer: 'c2', ack: 'auto' },
      { op: 'await.deliveries', count: 8 },
    ],
  },
  {
    id: 'delivery/prefetch-is-counted-for-each-consumer-of-a-channel',
    kind: 'delivery',
    title:
      'A channel that consumes from two queues has a window of its prefetch for each of its consumers, and not one to share (ADR-0008, rule 15)',
    steps: [
      declareQueue('a'),
      declareQueue('b'),
      { op: 'channel.open', channel: 'ch1', prefetch: 1 },
      { op: 'basic.consume', channel: 'ch1', queue: 'a', consumer: 'c1', ack: 'manual' },
      { op: 'basic.consume', channel: 'ch1', queue: 'b', consumer: 'c2', ack: 'manual' },
      publish('', 'a', 'm1'),
      publish('', 'a', 'm2'),
      publish('', 'b', 'm3'),
      publish('', 'b', 'm4'),
      { op: 'await.deliveries', count: 2 },
    ],
  },
  {
    id: 'delivery/closing-a-channel-requeues-what-a-cancelled-consumer-still-held',
    kind: 'delivery',
    title:
      'A consumer that was cancelled still holds its unacknowledged messages, and they are requeued as redelivered when its channel is closed (ADR-0008, rule 16)',
    steps: [
      declareQueue('jobs'),
      { op: 'channel.open', channel: 'ch1', prefetch: 2 },
      { op: 'basic.consume', channel: 'ch1', queue: 'jobs', consumer: 'c1', ack: 'manual' },
      publish('', 'jobs', 'm1'),
      publish('', 'jobs', 'm2'),
      publish('', 'jobs', 'm3'),
      { op: 'await.deliveries', count: 2 },
      { op: 'basic.cancel', consumer: 'c1' },
      { op: 'channel.close', channel: 'ch1' },
    ],
  },
  {
    id: 'delivery/each-queue-has-a-copy-and-each-copy-goes-to-one-consumer',
    kind: 'delivery',
    title:
      'A message that two queues receive is delivered once from each queue, and where a queue has two consumers, to one of them (ADR-0008, rules 7 and 13)',
    steps: [
      declareExchange('e', 'fanout'),
      declareQueue('q1'),
      declareQueue('q2'),
      bindKey('e', queue('q1'), ''),
      bindKey('e', queue('q2'), ''),
      { op: 'channel.open', channel: 'ch1' },
      { op: 'channel.open', channel: 'ch2' },
      { op: 'channel.open', channel: 'ch3' },
      { op: 'basic.consume', channel: 'ch1', queue: 'q1', consumer: 'c1', ack: 'auto' },
      { op: 'basic.consume', channel: 'ch2', queue: 'q2', consumer: 'c2', ack: 'auto' },
      { op: 'basic.consume', channel: 'ch3', queue: 'q1', consumer: 'c3', ack: 'auto' },
      publish('e', '', 'm1'),
      publish('e', '', 'm2'),
      { op: 'await.deliveries', count: 4 },
    ],
  },
];
