import type { Scenario } from '../scenario';
import {
  bindHeaders,
  bindKey,
  bool,
  declareQueue,
  entry,
  exchange,
  exists,
  float,
  int,
  publish,
  queue,
  str,
} from './helpers';

/**
 * Seed routing scenarios. They are inputs only: what the broker does with them is recorded into fixtures, and a
 * person reads the recording against ADR-0008 and ADR-0009. The full set arrives with the routing slice (S1).
 */
export const ROUTING_SCENARIOS: readonly Scenario[] = [
  {
    id: 'routing/direct-matches-the-whole-key-case-sensitively',
    kind: 'routing',
    title: 'A direct exchange routes on the whole routing key, and the comparison is case-sensitive (ADR-0008, rule 2)',
    steps: [
      { op: 'exchange.declare', name: 'orders', type: 'direct' },
      declareQueue('created'),
      declareQueue('created-too'),
      declareQueue('created-upper'),
      bindKey('orders', queue('created'), 'order.created'),
      bindKey('orders', queue('created-too'), 'order.created'),
      bindKey('orders', queue('created-upper'), 'ORDER.CREATED'),
      publish('orders', 'order.created', 'm1'),
      publish('orders', 'ORDER.CREATED', 'm2'),
      publish('orders', 'order', 'm3'),
      publish('orders', 'order.created.eu', 'm4'),
      publish('orders', '', 'm5'),
    ],
  },
  {
    id: 'routing/fanout-ignores-the-routing-key',
    kind: 'routing',
    title: 'A fanout exchange sends every message to every bound queue, whatever the routing key (ADR-0008, rule 3)',
    steps: [
      { op: 'exchange.declare', name: 'broadcast', type: 'fanout' },
      declareQueue('first'),
      declareQueue('second'),
      bindKey('broadcast', queue('first'), 'a'),
      bindKey('broadcast', queue('second'), 'b'),
      publish('broadcast', 'zzz', 'm1'),
      publish('broadcast', '', 'm2'),
    ],
  },
  {
    id: 'routing/topic-wildcards-match-whole-words',
    kind: 'routing',
    title:
      'A topic exchange splits keys into words: * is one word (possibly empty), # is zero or more (ADR-0008, rule 4)',
    steps: [
      { op: 'exchange.declare', name: 'events', type: 'topic' },
      declareQueue('star'),
      declareQueue('hash'),
      declareQueue('everything'),
      declareQueue('middle'),
      declareQueue('between'),
      declareQueue('literal'),
      bindKey('events', queue('star'), 'a.*'),
      bindKey('events', queue('hash'), 'a.#'),
      bindKey('events', queue('everything'), '#'),
      bindKey('events', queue('middle'), 'a.#.b'),
      bindKey('events', queue('between'), 'a.*.b'),
      bindKey('events', queue('literal'), 'a*'),
      publish('events', 'a', 'm1'),
      publish('events', 'a.b', 'm2'),
      publish('events', 'a.b.c', 'm3'),
      publish('events', 'a..b', 'm4'),
      publish('events', '', 'm5'),
      publish('events', 'a.x.y.b', 'm6'),
      publish('events', 'a*', 'm7'),
      publish('events', 'b', 'm8'),
    ],
  },
  {
    id: 'routing/default-exchange-routes-to-the-queue-with-that-name',
    kind: 'routing',
    title: 'The default exchange is bound to every queue, with the queue name as the key (ADR-0008, rule 6)',
    steps: [
      declareQueue('alpha'),
      declareQueue('beta'),
      publish('', 'alpha', 'm1'),
      publish('', 'beta', 'm2'),
      publish('', 'gamma', 'm3'),
      publish('', '', 'm4'),
    ],
  },
  {
    id: 'routing/an-exchange-with-no-bindings-returns-the-message',
    kind: 'routing',
    title: 'A mandatory message that no queue receives is returned to the publisher (ADR-0008, rules 10 and 12)',
    steps: [{ op: 'exchange.declare', name: 'nowhere', type: 'fanout' }, publish('nowhere', 'any', 'm1')],
  },
  {
    id: 'routing/exchange-to-exchange-bindings-follow-chains-and-survive-cycles',
    kind: 'routing',
    title:
      'Exchange-to-exchange bindings are followed, a cycle terminates, and a queue gets at most one copy (ADR-0008, rule 7)',
    steps: [
      { op: 'exchange.declare', name: 'e1', type: 'fanout' },
      { op: 'exchange.declare', name: 'e2', type: 'fanout' },
      { op: 'exchange.declare', name: 'e3', type: 'fanout' },
      declareQueue('qa'),
      declareQueue('qb'),
      bindKey('e1', exchange('e2'), ''),
      bindKey('e2', exchange('e3'), ''),
      bindKey('e3', exchange('e1'), ''),
      bindKey('e2', queue('qa'), ''),
      bindKey('e3', queue('qb'), ''),
      bindKey('e1', queue('qa'), ''),
      publish('e1', '', 'm1'),
      publish('e2', '', 'm2'),
      publish('e3', '', 'm3'),
    ],
  },
  {
    id: 'routing/headers-exchange-compares-typed-values',
    kind: 'routing',
    title: 'A headers exchange compares typed values: "1", 1, 1.0 and 64-bit 1 are tried against each other (ADR-0009)',
    steps: [
      { op: 'exchange.declare', name: 'docs', type: 'headers' },
      declareQueue('q-string'),
      declareQueue('q-int'),
      declareQueue('q-float'),
      declareQueue('q-int64'),
      declareQueue('q-bool'),
      declareQueue('q-exists'),
      declareQueue('q-any'),
      bindHeaders('docs', queue('q-string'), 'all', [entry('n', str('1'))]),
      bindHeaders('docs', queue('q-int'), 'all', [entry('n', int(1))]),
      bindHeaders('docs', queue('q-float'), 'all', [entry('n', float(1))]),
      bindHeaders('docs', queue('q-int64'), 'all', [entry('n', int(1, 64))]),
      bindHeaders('docs', queue('q-bool'), 'all', [entry('b', bool(true))]),
      bindHeaders('docs', queue('q-exists'), 'all', [entry('n', exists)]),
      bindHeaders('docs', queue('q-any'), 'any', [entry('n', int(1)), entry('b', bool(true))]),
      publish('docs', '', 'm1', [entry('n', str('1'))]),
      publish('docs', '', 'm2', [entry('n', int(1))]),
      publish('docs', '', 'm3', [entry('n', float(1))]),
      publish('docs', '', 'm4', [entry('n', int(1, 64))]),
      publish('docs', '', 'm5', [entry('b', bool(true))]),
      publish('docs', '', 'm6', []),
    ],
  },
];
